RAM-45
Exploit-Experts/RickAndMorty-Spring-API pull request #43
Opened 2024-11-19 00:11 UTC by brunoliratm

This pull request includes changes to enhance the functionality of the `LocationService` and `LocationController` classes by adding new filtering and sorting capabilities. Additionally, it simplifies the code by removing unused imports and annotations.

Enhancements to filtering and sorting:

* [`src/main/java/com/rickmorty/Controllers/LocationController.java`](diffhunk://#diff-ad55f1abc87f87648844e14fe29dd158eac4c62feff364a149e5603af2049071L6-R28): Added new request parameters (`name`, `type`, `dimension`, `sort`) to the `getAllLocations` method to enable filtering and sorting of locations.
* [`src/main/java/com/rickmorty/Services/LocationService.java`](diffhunk://#diff-9b0d4fcc9d85469e28ba6b966e8a3542a426cf78cead2b472ead9f3a6cab11b4L32-R46): Updated the `findAllLocations` method to accept and process the new filtering and sorting parameters. Added a new private method `compareLocations` to handle sorting logic. [[1]](diffhunk://#diff-9b0d4fcc9d85469e28ba6b966e8a3542a426cf78cead2b472ead9f3a6cab11b4L32-R46) [[2]](diffhunk://#diff-9b0d4fcc9d85469e28ba6b966e8a3542a426cf78cead2b472ead9f3a6cab11b4L79-R120)

Code simplification:

* [`src/main/java/com/rickmorty/Models/LocationModel.java`](diffhunk://#diff-c644fd154bef6066788efb2e2fedc00189e8e08f6267c744168c45def208917eL3-L6): Removed unused Jackson annotations.
* [`src/main/java/com/rickmorty/Services/LocationService.java`](diffhunk://#diff-9b0d4fcc9d85469e28ba6b966e8a3542a426cf78cead2b472ead9f3a6cab11b4L17): Removed unused imports and the `@Autowired` annotation from the constructor. [[1]](diffhunk://#diff-9b0d4fcc9d85469e28ba6b966e8a3542a426cf78cead2b472ead9f3a6cab11b4L17) [[2]](diffhunk://#diff-9b0d4fcc9d85469e28ba6b966e8a3542a426cf78cead2b472ead9f3a6cab11b4L32-R46)

2024-11-19 22:34 UTC, Paulo-Araujo-Jr approved these changes
Mensagem:

O Pull Request foi revisado e está de acordo com as diretrizes do projeto. As alterações propostas foram testadas, e o impacto foi avaliado. Nenhum problema foi identificado, e a implementação segue as melhores práticas.

Aprovado para merge! 🚀

2024-11-20 03:19 UTC, MrMesquita commented on src/main/java/com/rickmorty/enums/SortLocation.java
> +    name_asc,
Por enum se tratar de constantes por padrão tem que ficar tudo em upper case, ex: NAME_ASC

2024-11-20 03:20 UTC, MrMesquita requested changes
Deixei um comentário

2024-11-20 14:28 UTC, MrMesquita approved these changes

2024-11-20 14:28 UTC, merged